//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public string EmployeeName { get; set; }
        public int ID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<bool> IsPresent { get; set; }
    }
}
